apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: 549558686534.dkr.ecr.ca-central-1.amazonaws.com/user17-order
        name: guestbook-ui
        ports:
        - containerPort: 80
